### ISSUE TITLE
imports seem to be evaluated relative to the last import's directory

### ISSUE THREAD

**Issue by slang800** [LearnBoost/stylus#1802] opened 2015-01-06 00:25 UTC
I have a file at `./case_studies/all.styl` that needs to import `./_settings.styl` and all the other files in `./case_studies`. So I write these 2 lines:

```
@import '../_settings'
@import './*'
```

`_settings.styl` seems to be imported correctly, but after that it imports all the files under `./`, rather than all the files under `./case_studies`. If I change `./case_studies/all.styl` to say:

```
@import '../_settings'
@import './case_studies/*'
```

Then it does what I wanted it to, but is obviously wrong because there is nothing at `./case_studies/case_studies/*`. And if I remove the first line, then the 2nd line produces the error "failed to locate @import file ./case_studies/*.styl".

**Comment by Panya** [comment] 2015-01-06 08:40
Duplicate of #1403

**Closed by Panya** 2015-01-06 08:40 UTC
