### ISSUE TITLE
support cascading extend 

### ISSUE THREAD

**Issue by supersheep** [LearnBoost/stylus#1304] opened 2013-12-28 02:59 UTC
```
$a
	color:#c00
$b
	color:#019
	.a
		@extend $a

.a
	@extend $b
.c 
	@extend $b
```

and I expect to see this yields to:
```
.a,.c{
	color:#019;
}
.a .a,
.c .a{
	color:#c00;
}
```

but acturally what I got is just

```
.a,
.c {
  color: #019;
}
```

**Comment by Panya** [comment] 2015-02-07 01:37
Duplicate of #571

**Closed by Panya** 2015-02-07 01:37 UTC
