### ISSUE TITLE
@extend bugs in block mixins

### ISSUE THREAD

**Issue by firede** [LearnBoost/stylus#1862] opened 2015-03-17 06:01 UTC
Source:
```styl
foo()
  .lol
    {block}
.foo
  height: 40px

.bar
  +foo()
    @extend .foo
```

Output:
```css
.foo,
.bar {
  height: 40px;
}
```

Expect:
```css
.foo,
.bar .lol {
  height: 40px;
}
```

_version: 0.50.0_

**Comment by Panya** [comment] 2015-03-17 08:32
Duplicate of #1507 (there is a workaround).

**Closed by Panya** 2015-03-17 08:32 UTC
