### ISSUE TITLE
@media block with @import as sole member gets dropped

### ISSUE THREAD

**Issue by yourcelf** [LearnBoost/stylus#1850] opened 2015-02-20 22:59 UTC
If you have a @media block with no members other than an @import statement, the @import gets dropped.

    @media print
      @import "print.styl"

Acutal output: nothing.

Expected output:

    @media print {
      // contents of "print.styl"
      body {
        font-size: 18px;
      }
    }

Adding any additional rule to the @media block causes it to work as expected:

    @media print
      html
        color inherit
      @import "print.styl"

Output:

    @media print {
      html {
        color: inherit;
      }
    // contents of "print.styl"
    body {
      font-size: 18px;
    }
    }

**Comment by Panya** [comment] 2015-02-20 23:13
Which version of Stylus are you using? I can't reproduce this with the latest version (0.50.0).

**Comment by yourcelf** [comment] 2015-02-21 00:44
I'm running v0.50.0.  But my apologies, the bug is slightly more specific than I represented.  It seems to be triggered only when the eventual contents of the ``@media`` block after importing all stylus is a single CSS import, e.g.:

    // test.styl
    @media print
        @import "somefile.css"

The same result happens if you import a stylus file, the contents of which is a single-line css import, e.g.:

    // test.styl
    @media print
        @import print.styl

    // print.styl
    @import "somefile.css"

The output if there is some other declaration either in the original ``@media`` block or in the imported stylus file is the following:

    @media print {
        @import("somefile.css");
        ... other declarations ...;
    }

This is in fact invalid CSS -- ``@import`` can't be nested inside a ``@media`` block in CSS that way.  The correct way to ``@import`` for a particular media type would be ``@import(<URL>) (<media-query>);``.  In my case, this invalid CSS is convenient for me because I'm piping stylus's output into something that inlines the CSS, so I get the result I want -- but you might prefer to fix the invalid CSS instead.

Either way, it's odd that the css ``@import`` is suppressed unless there is some other style declaration in the media block.

**Comment by Panya** [comment] 2015-02-21 01:23
> Either way, it's odd that the css @import is suppressed unless there is some other style declaration in the media block.

Yep, I've fixed this bug in the `dev` branch. The fix will be in the next release. Thanks for the report.

**Closed by Panya** 2015-02-21 01:23 UTC
Labels: t: Bug
