### ISSUE TITLE
Incorrect behaviour with @extend inside @media

### ISSUE THREAD

**Issue by rzcoder** [LearnBoost/stylus#1845] opened 2015-02-18 21:39 UTC
Rules using @extend inside @media yield incorrect results:

```
.basic_flex
  display: flex

@media (min-width: 100px)
  body
    @extend .basic_flex
    justify-content: flex-start
```
Yielding:
```
.basic_flex,
body {
  display: flex;
}
@media (min-width: 100px) {
  body {
    justify-content: flex-start;
  }
}
```

**Comment by Panya** [comment] 2015-02-18 21:41
Duplicate of #1095

**Closed by Panya** 2015-02-18 21:41 UTC
