### ISSUE TITLE
stylus@0.48.1+ breaks require

### ISSUE THREAD

**Issue by stevelacy** [LearnBoost/stylus#1832] opened 2015-02-05 01:06 UTC
versions after 0.48.1 have an error where compiling subsequent builds of files which require sibling files are unable to correctly require the code.

Example: https://github.com/stevelacy/stylus-bug-99

The gulpfile contains a pure stylus function which compiles from the `gulp.src`.
It succeeds on the initial run, but following builds break.

The error returned:

```shell
1| @require "vars"
   2|
   3| html
   4|   color green
   5|   font-size (font-size-base / 16)rem
------------------------------------^
   6|

cannot perform font-size-base / 16
    at "html" (/Users/simonsmith/Sites/stylus-bug/styl/base/base.styl:2:16)
```
This seems to indicate that the file path, or require path is altered upon initial run.

Error report: https://github.com/stevelacy/gulp-stylus/issues/99

**Comment by Panya** [comment] 2015-02-05 03:08
Hmm, I can't reproduce this.

```
git clone https://github.com/stevelacy/stylus-bug-99.git
cd stylus-bug-99
npm i
...
gulp stylus
[05:58:59] Using gulpfile /stylus-bug-99/gulpfile.js
[05:58:59] Starting 'stylus'...
null 'html {\n  color: #008000;\n  font-size: 0.875rem;\n}\n'
null ''
[05:58:59] Finished 'stylus' after 127 ms
gulp stylus
[05:59:01] Using gulpfile /stylus-bug-99/gulpfile.js
[05:59:01] Starting 'stylus'...
null 'html {\n  color: #008000;\n  font-size: 0.875rem;\n}\n'
null ''
[05:59:01] Finished 'stylus' after 107 ms
```
And after editing the file and rebuild again all works fine (without an error).

Stylus 0.49.3
Gulp 3.8.10
Node 0.10.31

**Comment by stevelacy** [comment] 2015-02-05 03:16
I'm sorry, forgot to mention that the task name to produce the watch clause is `gulp watch`

```
[19:14:45] Using gulpfile ~/Desktop/stylus-bug-99/gulpfile.js
[19:14:45] Starting 'watch'...
[19:14:45] Finished 'watch' after 5.92 ms
[19:15:27] Starting 'stylus'...
null 'html {\n  color: #008000;\n  font-size: 0.875rem;\n}\n'
null ''
[19:15:27] Finished 'stylus' after 70 ms
[19:15:30] Starting 'stylus'...
[19:15:30] gulp-notify: [Compile Error] /home/sl/Desktop/stylus-bug-99/styl/base/base.styl:5:31
   1| @require "vars"
   2| 
   3| html
   4|   color green
   5|   font-size (font-size-base / 16)rem
------------------------------------^
   6| 

cannot perform font-size-base / 16
    at "html" (/home/sl/Desktop/stylus-bug-99/styl/base/base.styl:2:16)

[19:15:30] Finished 'stylus' after 12 ms

```

**Comment by Panya** [comment] 2015-02-05 04:58
Yep, confirmed. I've fixed this bug in the `dev` branch. This fix will be in the next release. Thanks for the report.

**Closed by Panya** 2015-02-05 04:58 UTC
Labels: t: Bug

**Comment by stevelacy** [comment] 2015-02-05 05:38
Excellent thanks!
