### ISSUE TITLE
@extend in sub-block of placeholder selector doesn't ouput

### ISSUE THREAD

**Issue by donut** [LearnBoost/stylus#1864] opened 2015-03-18 21:38 UTC
For example, I would expect the Stylus code

```stylus
$purdy
  color red

$big-thing
  background gray
  a:visited
    @extends $purdy

.best-thing
  @extends $big-thing
```

to compile to

```css
.best-thing {
  background: #808080;
}

.best-thing a:visited {
  color: #f00;
}
```

but it comes out as 

```css
.best-thing {
  background: #808080;
}
```

completely missing the `a:visited` block. Is there any way around this?

**Comment by Panya** [comment] 2015-03-18 21:46
Duplicate of #571. Already fixed in the `dev` branch. The fix will be in the next release.

**Closed by Panya** 2015-03-18 21:46 UTC

**Comment by donut** [comment] 2015-03-18 21:47
Great! Sorry to post a duplicate.
