### ISSUE TITLE
Can't extend a nested selector that extends another selector

### ISSUE THREAD

**Issue by joeldrapper** [LearnBoost/stylus#1839] opened 2015-02-12 13:01 UTC
```styl
.headingLink
	color inherit
	text-decoration none

.alpha
	font-weight bold
	a
		@extend .headingLink

.beta
	font-weight bold
	font-style italic
	a
		@extend .headingLink

h1
	@extend .alpha

h2
	@extend .beta
```

Any idea how I can get around this?

**Comment by Panya** [comment] 2015-02-12 13:19
Duplicate of #571. This bug already fixed in the `dev` branch. The fix will be in the next release.

**Closed by Panya** 2015-02-12 13:19 UTC
