### ISSUE TITLE
Bug with class inheritance

### ISSUE THREAD

**Issue by alexmironov** [LearnBoost/stylus#1162] opened 2013-10-16 19:00 UTC
Example code:
```
.clear
	width 100%
	height 0
	overflow hidden
	font-size 0
	clear both
	display block

.cleared
	&:after
		content ""
		@extend .clear

.myclass
	@extend .cleared
```

As result we have:
```
.myclass:after {content:""}
```
and no styles inherited from .clear

**Comment by Panya** [comment] 2015-02-07 01:37
Duplicate of #571

**Closed by Panya** 2015-02-07 01:37 UTC
Labels: t: Bug
