### ISSUE TITLE
bug: extending and parent selectors

### ISSUE THREAD

**Issue by ianstormtaylor** [LearnBoost/stylus#749] opened 2012-07-12 03:31 UTC
i have the following:

```
.rd
    purple: red

.rod
    line-height: 0em
    &:hover
        font-weight: 900
        @extend .rd

.rood
    color: blue
    &.pressed
        width: 1px
        @extend .rod
```

with stylus it compiles to:

```
.rd,
.rod:hover {
  purple: #f00;
}
.rod,
.rood.pressed {
  line-height: 0em;
}
.rod:hover,
.rood.pressed:hover {
  font-weight: 900;
}
.rood {
  color: #00f;
}
.rood.pressed {
  width: 1px;
}
```

with sass it compiles to:

```
.rd, 
.rod:hover, 
.rood.pressed:hover { /* the important extra selector generated */
  purple: red; 
}
.rod, 
.rood.pressed {
  line-height: 0em; 
}
.rod:hover, 
.rood.pressed:hover {
    font-weight: 900; 
}
.rood {
  color: blue; 
}
.rood.pressed {
    width: 1px; 
}

```

**Comment by Panya** [comment] 2015-02-07 01:37
Duplicate of #571

**Closed by Panya** 2015-02-07 01:37 UTC
Labels: t: Bug
